matrix:
  include:
  - name: "Pylint on Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    env: [TARGET="pylint", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Fedora Core 30 (Docker) with Python 2.7"
    env: FEDORA_VERSION="30"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    services:
    - docker
  - name: "Fedora Core 30 (Docker) with Python 3.7"
    env: FEDORA_VERSION="30"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.7
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 2.7"
    env: [TARGET="coverage", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    env: UBUNTU_VERSION="18.04"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "MacOS with Python 2.7.10"
    env: [TARGET="macos-python27", PYTHONPATH="/Library/Python/2.7/site-packages/"]
    os: osx
    osx_image: xcode9.2
    language: generic
install:
- ./config/travis/install.sh
script:
- ./config/travis/run_with_timeout.sh 30 ./config/travis/runtests.sh
